version: "3.3"
services:
  node:
    image: ${NODE_IMAGE}
    container_name: ${STACK_NAME}.node
    user: ${LOCAL_USER_UID}:${LOCAL_USER_GID}
    command: /bin/bash -c "while [ 1 ]; do sleep 3600; done"
    working_dir: ${DATA_PATH_PREFIX}
    tty: true
    ports:
      - 9191:8080
    volumes:
      - ${PWD}:${DATA_PATH_PREFIX}:delegated
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${API_PORT}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
    links:
      - redis:redis

  api:
    build:
      dockerfile: ${PWD}/app/Dockerfile
      context: ./app
      args:
        - NODE_IMAGE=${NODE_IMAGE}
    container_name: ${STACK_NAME}.api
#    working_dir: ${DATA_PATH_PREFIX}
#  command: node app/api/api.js
    user: ${LOCAL_USER_UID}:${LOCAL_USER_GID}
    tty: true
    ports:
      - 9090:8080
#    volumes:
#        - ${PWD}:${DATA_PATH_PREFIX}:delegated
    environment:
        - NODE_ENV=prod
        - PORT=${API_PORT}
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_HOST=${REDIS_HOST}
    links:
      - redis:redis

  redis:
    image: ${REDIS_IMAGE}
    container_name: ${STACK_NAME}.redis
    command: redis-server --save "" --appendonly no
    user: ${LOCAL_USER_UID}:${LOCAL_USER_GID}
    tty: true
    ports:
      - 9093:6379
